# packages/device_in_use.yaml

number:
  - platform: template
    name: "${friendly_name} Device In Use Threshold"
    id: device_in_use_threshold
    entity_category: config
    unit_of_measurement: W
    mode: box
    min_value: 1
    max_value: 500
    step: 1
    initial_value: 20
    restore_value: true
    optimistic: true

  - platform: template
    name: "${friendly_name} Device In Use On Delay"
    id: device_in_use_on_delay
    entity_category: config
    unit_of_measurement: s
    mode: box
    min_value: 0
    max_value: 600
    step: 5
    initial_value: 30
    restore_value: true
    optimistic: true

  - platform: template
    name: "${friendly_name} Device In Use Off Delay"
    id: device_in_use_off_delay
    entity_category: config
    unit_of_measurement: s
    mode: box
    min_value: 0
    max_value: 3600
    step: 30
    initial_value: 600
    restore_value: true
    optimistic: true

binary_sensor:
  - platform: template
    name: "${friendly_name} – Active Load"
    id: device_in_use
    lambda: |-
      return id(power).state > id(device_in_use_threshold).state;
    filters:
      - delayed_on: !lambda "return (uint32_t)(id(device_in_use_on_delay).state * 1000);"
      - delayed_off: !lambda "return (uint32_t)(id(device_in_use_off_delay).state * 1000);"
